spring:
  threads:
    virtual:
      enabled: true
  application:
    name: notification-gateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated # RabbitMQ cluster informs producer about published message
    template:
      mandatory: true # If message is NOT routable, rabbitMq calls callback: rabbitTemplate.setReturnsCallback(returned -> {...});
    virtual-host: notification

app:
  services:
    notification-template-service:
      url: http://localhost:8081
      basic-auth:
        username: admin
        password: admin123
  rabbitmq:
    exchanges:
      internal: notification.internal.exchange
      audit: notification.audit.exchange
    queues:
      sms: notification.sms.queue
      fcm: notification.fcm.queue
      hcm: notification.hcm.queue