spring:
  threads:
    virtual:
      enabled: true
  application:
    name: notification-gateway-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  services:
    notification-template-service:
      url: http://localhost:8081
  rabbitmq:
    queues:
      sms: notification.sms.queue
      fcm: notification.fcm.queue
      hcm: notification.hcm.queue
      event: notification.events.queue